---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # CentOS 6 OpenJDK
  - name: centos-6-default
    image: centos:6
  - name: centos-6-openjdk-6-jre
    image: centos:6
  - name: centos-6-openjdk-6-jdk
    image: centos:6
  - name: centos-6-openjdk-7-jre
    image: centos:6
  - name: centos-6-openjdk-7-jdk
    image: centos:6
  - name: centos-6-openjdk-8-jre
    image: centos:6
  - name: centos-6-openjdk-8-jdk
    image: centos:6
  # CentOS 6 Oracle
  - name: centos-6-oracle-8-jre
    image: centos:6
  - name: centos-6-oracle-8-jdk
    image: centos:6
  - name: centos-6-oracle-9-jre
    image: centos:6
  - name: centos-6-oracle-9-jdk
    image: centos:6
  # CentOS 7 OpenJDK
  - name: centos-7-default
    image: centos:7
  - name: centos-7-openjdk-6-jre
    image: centos:7
  - name: centos-7-openjdk-6-jdk
    image: centos:7
  - name: centos-7-openjdk-7-jre
    image: centos:7
  - name: centos-7-openjdk-7-jdk
    image: centos:7
  - name: centos-7-openjdk-8-jre
    image: centos:7
  - name: centos-7-openjdk-8-jdk
    image: centos:7
  # CentOS 7 Oracle
  - name: centos-7-oracle-8-jre
    image: centos:7
  - name: centos-7-oracle-8-jdk
    image: centos:7
  - name: centos-7-oracle-9-jre
    image: centos:7
  - name: centos-7-oracle-9-jdk
    image: centos:7
  # Debian Jessie OpenJDK
  - name: debian-8-default
    image: debian:jessie
  - name: debian-8-openjdk-7-jre
    image: debian:jessie
  - name: debian-8-openjdk-7-jdk
    image: debian:jessie
  # Debian Jessie Oracle
  - name: debian-8-oracle-8-jre
    image: debian:jessie
  - name: debian-8-oracle-8-jdk
    image: debian:jessie
  - name: debian-8-oracle-9-jre
    image: debian:jessie
  - name: debian-8-oracle-9-jdk
    image: debian:jessie
  # Debian Buster openjdk
  - name: debian-buster-openjdk-8-jre
    image: debian:buster
  - name: debian-buster-openjdk-8-jdk
    image: debian:buster
  - name: debian-buster-openjdk-9-jre
    image: debian:buster
  - name: debian-buster-openjdk-9-jdk
    image: debian:buster
  # Debian Buster Oracle
  - name: debian-buster-oracle-8-jre
    image: debian:buster
  - name: debian-buster-oracle-8-jdk
    image: debian:buster
  - name: debian-buster-oracle-9-jre
    image: debian:buster
  - name: debian-buster-oracle-9-jdk
    image: debian:buster
  # Fedora 26 OpenJDK
  - name: fedora-26-openjdk-8-jre
    image: fedora:26
  - name: fedora-26-openjdk-8-jdk
    image: fedora:26
  - name: fedora-26-openjdk-9-jre
    image: fedora:26
  - name: fedora-26-openjdk-9-jdk
    image: fedora:26
  # Fedora 26 Oracle
  - name: fedora-26-oracle-8-jre
    image: fedora:26
  - name: fedora-26-oracle-8-jdk
    image: fedora:26
  - name: fedora-26-oracle-9-jre
    image: fedora:26
  - name: fedora-26-oracle-9-jdk
    image: fedora:26
  # Fedora 27 OpenJDK
  - name: fedora-27-openjdk-8-jre
    image: fedora:27
  - name: fedora-27-openjdk-8-jdk
    image: fedora:27
  - name: fedora-27-openjdk-9-jre
    image: fedora:27
  - name: fedora-27-openjdk-9-jdk
    image: fedora:27
  # Fedora 27 Oracle
  - name: fedora-27-oracle-8-jre
    image: fedora:27
  - name: fedora-27-oracle-8-jdk
    image: fedora:27
  - name: fedora-27-oracle-9-jre
    image: fedora:27
  - name: fedora-27-oracle-9-jdk
    image: fedora:27
  # Ubuntu 17 OpenJDK
  - name: ubuntu-17-openjdk-8-jre
    image: ubuntu:zesty
  - name: ubuntu-17-openjdk-8-jdk
    image: ubuntu:zesty
  - name: ubuntu-17-openjdk-9-jre
    image: ubuntu:zesty
  - name: ubuntu-17-openjdk-9-jdk
    image: ubuntu:zesty
  # Ubuntu 17 oracle
  - name: ubuntu-17-oracle-8-jre
    image: ubuntu:zesty
  - name: ubuntu-17-oracle-8-jdk
    image: ubuntu:zesty
  - name: ubuntu-17-oracle-9-jre
    image: ubuntu:zesty
  - name: ubuntu-17-oracle-9-jdk
    image: ubuntu:zesty
  # Ubuntu 18 OpenJDK
  - name: ubuntu-18-openjdk-8-jre
    image: ubuntu:artful
  - name: ubuntu-18-openjdk-8-jdk
    image: ubuntu:artful
  - name: ubuntu-18-openjdk-9-jre
    image: ubuntu:artful
  - name: ubuntu-18-openjdk-9-jdk
    image: ubuntu:artful
  # Ubuntu 18 oracle
  - name: ubuntu-18-oracle-8-jre
    image: ubuntu:artful
  - name: ubuntu-18-oracle-8-jdk
    image: ubuntu:artful
  - name: ubuntu-18-oracle-9-jre
    image: ubuntu:artful
  - name: ubuntu-18-oracle-9-jdk
    image: ubuntu:artful
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: 'None'
