---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # CentOS 6 OpenJDK
  - name: centos-6-default
    image: centos:6
  - name: centos-6-openjdk-6-jre
    image: centos:6
  - name: centos-6-openjdk-6-jdk
    image: centos:6
  - name: centos-6-openjdk-7-jre
    image: centos:6
  - name: centos-6-openjdk-7-jdk
    image: centos:6
  - name: centos-6-openjdk-8-jre
    image: centos:6
  - name: centos-6-openjdk-8-jdk
    image: centos:6
  # CentOS 7 OpenJDK
  - name: centos-7-default
    image: centos:7
  - name: centos-7-openjdk-6-jre
    image: centos:7
  - name: centos-7-openjdk-6-jdk
    image: centos:7
  - name: centos-7-openjdk-7-jre
    image: centos:7
  - name: centos-7-openjdk-7-jdk
    image: centos:7
  - name: centos-7-openjdk-8-jre
    image: centos:7
  - name: centos-7-openjdk-8-jdk
    image: centos:7
  # Debian Jessie openjdk
  - name: debian-jessie-default
    image: debian:jessie
  - name: debian-jessie-openjdk-7-jre
    image: debian:jessie
  - name: debian-jessie-openjdk-7-jdk
    image: debian:jessie
  # Debian Buster openjdk
  - name: debian-buster-openjdk-8-jre
    image: debian:buster
  - name: debian-buster-openjdk-8-jdk
    image: debian:buster
  - name: debian-buster-openjdk-9-jre
    image: debian:buster
  - name: debian-buster-openjdk-9-jdk
    image: debian:buster
  # Fedora 26 OpenJDK
  - name: fedora-26-openjdk-8-jre
    image: fedora:26
  - name: fedora-26-openjdk-8-jdk
    image: fedora:26
  - name: fedora-26-openjdk-9-jre
    image: fedora:26
  - name: fedora-26-openjdk-9-jdk
    image: fedora:26
  # Fedora 27 OpenJDK
  - name: fedora-27-openjdk-8-jre
    image: fedora:27
  - name: fedora-27-openjdk-8-jdk
    image: fedora:27
  - name: fedora-27-openjdk-9-jre
    image: fedora:27
  - name: fedora-27-openjdk-9-jdk
    image: fedora:27
  # Ubuntu 17 openjdk
  - name: ubuntu-17-openjdk-8-jre
    image: ubuntu:zesty
  - name: ubuntu-17-openjdk-8-jdk
    image: ubuntu:zesty
  - name: ubuntu-17-openjdk-9-jre
    image: ubuntu:zesty
  - name: ubuntu-17-openjdk-9-jdk
    image: ubuntu:zesty
  # Ubuntu 18 OpenJDK
  - name: ubuntu-18-openjdk-8-jre
    image: ubuntu:artful
  - name: ubuntu-18-openjdk-8-jdk
    image: ubuntu:artful
  - name: ubuntu-18-openjdk-9-jre
    image: ubuntu:artful
  - name: ubuntu-18-openjdk-9-jdk
    image: ubuntu:artful

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: travis
verifier:
  name: goss
  lint:
    name: 'None'
