---
### CentOS 6 OpenJDK
- name: install centos 6 default
  hosts: centos-6-default
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java

- name: install centos 6 openjdk 6 jre
  hosts: centos-6-openjdk-6-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 6

- name: install centos 6 openjdk 6 jdk
  hosts: centos-6-openjdk-6-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 6
      java_type: jdk

- name: install centos 6 openjdk 7 jre
  hosts: centos-6-openjdk-7-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 7

- name: install centos 6 openjdk 7 jdk
  hosts: centos-6-openjdk-7-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 7
      java_type: jdk

- name: install centos 6 openjdk 8 jre
  hosts: centos-6-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8

- name: install centos 6 openjdk 8 jdk
  hosts: centos-6-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8
      java_type: jdk

### CentOS 7 OpenJDK
- name: install centos 7 default
  hosts: centos-7-default
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java

- name: install centos 7 openjdk 6 jre
  hosts: centos-7-openjdk-6-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 6

- name: install centos 7 openjdk 6 jdk
  hosts: centos-7-openjdk-6-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 6
      java_type: jdk

- name: install centos 7 openjdk 7 jre
  hosts: centos-7-openjdk-7-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 7

- name: install centos 7 openjdk 7 jdk
  hosts: centos-7-openjdk-7-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 7
      java_type: jdk

- name: install centos 7 openjdk 8 jre
  hosts: centos-7-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8

- name: install centos 7 openjdk 8 jdk
  hosts: centos-7-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8
      java_type: jdk

### Debian Jessie OpenJDK
- name: install debian jessie default
  hosts: debian-jessie-default
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java

- name: install debian jessie openjdk 7 jre
  hosts: debian-jessie-openjdk-7-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 7

- name: install debian jessie openjdk 7 jdk
  hosts: debian-jessie-openjdk-7-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 7
      java_type: jdk

### Debian Buster OpenJDK
- name: install debian buster openjdk 8 jre
  hosts: debian-buster-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8

- name: install debian buster openjdk 8 jdk
  hosts: debian-buster-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8
      java_type: jdk

- name: install debian buster openjdk 9 jre
  hosts: debian-buster-openjdk-9-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9

- name: install debian buster openjdk 9 jdk
  hosts: debian-buster-openjdk-9-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9
      java_type: jdk

### Fedora 26 OpenJDK
- name: install fedora 26 openjdk 8 jre
  hosts: fedora-26-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8

- name: install fedora 26 openjdk 8 jdk
  hosts: fedora-26-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8
      java_type: jdk

- name: install fedora 26 openjdk 9 jre
  hosts: fedora-26-openjdk-9-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9

- name: install fedora 26 openjdk 9 jdk
  hosts: fedora-26-openjdk-9-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9
      java_type: jdk

### Fedora 27 OpenJDK
- name: install fedora 27 openjdk 8 jre
  hosts: fedora-27-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8

- name: install fedora 27 openjdk 8 jdk
  hosts: fedora-27-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8
      java_type: jdk

- name: install fedora 27 openjdk 9 jre
  hosts: fedora-27-openjdk-9-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9

- name: install fedora 27 openjdk 9 jdk
  hosts: fedora-27-openjdk-9-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9
      java_type: jdk

### Ubuntu 17 OpenJDK
- name: install ubuntu 17 openjdk 8 jre
  hosts: ubuntu-17-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8

- name: install ubuntu 17 openjdk 8 jdk
  hosts: ubuntu-17-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8
      java_type: jdk

- name: install ubuntu 17 openjdk 9 jre
  hosts: ubuntu-17-openjdk-9-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9

- name: install ubuntu 17 openjdk 9 jdk
  hosts: ubuntu-17-openjdk-9-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9
      java_type: jdk

### Ubuntu 18 OpenJDK
- name: install ubuntu 18 openjdk 8 jre
  hosts: ubuntu-18-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8

- name: install ubuntu 18 openjdk 8 jdk
  hosts: ubuntu-18-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 8
      java_type: jdk

- name: install ubuntu 18 openjdk 9 jre
  hosts: ubuntu-18-openjdk-9-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9

- name: install ubuntu 18 openjdk 9 jdk
  hosts: ubuntu-18-openjdk-9-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_vendor: openjdk
      java_version: 9
      java_type: jdk
